#Message Types

class ControlMessageTypes():
    GET_NEXT_NODE = 0
    GET_ROOT_NODE_REQUEST = 1
    IS_SUCCESSOR = 2
    IS_PREDECESSOR = 3
    GET_PREDECESSOR = 4
    UPDATE_FINGER_TABLE = 5
    GET_NEXT_NODE_PREDECESSOR = 6
    PUBLISHER_HERE_FIND_MY_SUCCESSOR = 10
    SUBSCRIBER_HERE_FIND_MY_SUCCESSOR = 11
    PUBLISHERHERE_STOREOWN_STRENGTH = 12
    SUBSCRIBER_HERE_STORE_ME = 13
    PUBLISH = 14
    PUBLISHERDEAD = 15
    SUBSCRIBERDEAD = 16


class MessageTypes():
    MSG_ACK = 8
    PING = 9
    
